apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-sidekiq
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app: uffizzi-sidekiq

spec:
  replicas: {{ .Values.sidekiq.replicas }}
  selector:
    matchLabels:
      app: uffizzi-sidekiq

  template:
    metadata:
      labels: {{ include "common.labels.standard" . | nindent 8 }}
        app: uffizzi-sidekiq
    spec:
      automountServiceAccountToken: false
      {{- include "sidekiq.renderImagePullSecrets" . | nindent 6 }}
      containers:
      - name: uffizzi-sidekiq
        image: {{ include "sidekiq.image" . }}
        imagePullPolicy: {{ .Values.sidekiq.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        args:
        - bundle exec sidekiq -C /app/config/sidekiq.yml
        envFrom:
        - secretRef:
            name: uffizzi-web-secret-envs
            optional: false
        - configMapRef:
            name: uffizzi-web-common-envs
            optional: false
        - configMapRef:
            name: uffizzi-web-sidekiq-envs
            optional: false
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 400m
            memory: 800Mi
