name: Uffizzi Core Release
on:
  push:
    tags:
      - core_v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.0
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1.3
      - name: Release Gem
        run: docker compose run --rm core bash -c "make release_gem"
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: core
          push: true
          tags: uffizzi/core:${{ github.ref_name }}
